// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkavAk48ikyuG69ueFqH-YG0K-2rdjBM',
    appId: '1:89760763575:web:70b11a410e3a4b86c7c732',
    messagingSenderId: '89760763575',
    projectId: 'wysa-clone',
    authDomain: 'wysa-clone.firebaseapp.com',
    storageBucket: 'wysa-clone.firebasestorage.app',
    measurementId: 'G-3HRKHKCW08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTheAnuXDznP-nyM8HKCtJ35a6u0RobZY',
    appId: '1:89760763575:android:9e44e18b7ff8e14ec7c732',
    messagingSenderId: '89760763575',
    projectId: 'wysa-clone',
    storageBucket: 'wysa-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwjtAz5GwG5M0Ni7XWyAo8HsLpT3aWqA',
    appId: '1:89760763575:ios:f738e09a4ad0e21ac7c732',
    messagingSenderId: '89760763575',
    projectId: 'wysa-clone',
    storageBucket: 'wysa-clone.firebasestorage.app',
    iosClientId: '89760763575-s8pkbjh13974io4dg6j47tj65c755g39.apps.googleusercontent.com',
    iosBundleId: 'com.example.wysaApp',
  );

}